"""Initial migration

Revision ID: 3b7a973c064d
Revises: 
Create Date: 2026-06-13 19:34:52.357849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7a973c064d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_genres_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('listener', 'artist', 'admin', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('artists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('monthly_listeners', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_stage_name'), ['stage_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_artists_user_id'), ['user_id'], unique=True)

    op.create_table('playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlists_title'), ['title'], unique=False)

    op.create_table('albums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('album_type', sa.Enum('album', 'single', 'ep', 'compilation', name='album_types'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_albums_title'), ['title'], unique=False)

    op.create_table('user_followed_artists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'artist_id')
    )
    with op.batch_alter_table('user_followed_artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_followed_artists_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_followed_artists_user_id'), ['user_id'], unique=False)

    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('duration_secs', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_songs_title'), ['title'], unique=False)

    op.create_table('play_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('duration_played_secs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play_history_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_play_history_user_id'), ['user_id'], unique=False)

    op.create_table('playlist_songs',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id')
    )
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_songs_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_songs_song_id'), ['song_id'], unique=False)

    op.create_table('song_genres',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'genre_id')
    )
    with op.batch_alter_table('song_genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_genres_genre_id'), ['genre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_genres_song_id'), ['song_id'], unique=False)

    op.create_table('user_liked_songs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    with op.batch_alter_table('user_liked_songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_liked_songs_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_liked_songs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_liked_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_liked_songs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_liked_songs_song_id'))

    op.drop_table('user_liked_songs')
    with op.batch_alter_table('song_genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_genres_song_id'))
        batch_op.drop_index(batch_op.f('ix_song_genres_genre_id'))

    op.drop_table('song_genres')
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_songs_song_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_songs_playlist_id'))

    op.drop_table('playlist_songs')
    with op.batch_alter_table('play_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_play_history_song_id'))

    op.drop_table('play_history')
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_title'))
        batch_op.drop_index(batch_op.f('ix_songs_artist_id'))
        batch_op.drop_index(batch_op.f('ix_songs_album_id'))

    op.drop_table('songs')
    with op.batch_alter_table('user_followed_artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_followed_artists_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_followed_artists_artist_id'))

    op.drop_table('user_followed_artists')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_title'))
        batch_op.drop_index(batch_op.f('ix_albums_artist_id'))

    op.drop_table('albums')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_title'))
        batch_op.drop_index(batch_op.f('ix_playlists_owner_id'))

    op.drop_table('playlists')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_user_id'))
        batch_op.drop_index(batch_op.f('ix_artists_stage_name'))

    op.drop_table('artists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_slug'))
        batch_op.drop_index(batch_op.f('ix_genres_name'))

    op.drop_table('genres')
    # ### end Alembic commands ###
